### ISSUE TITLE
create-graphql-app

### ISSUE THREAD

**Issue by Urigo** [tomyitav/graphql-server-typed#3]
Hi @tomyitav and @AlonShirion , how are you??? :)

What do you think about making this server boilerplate even cooler?
Instead of just a server boilerplate that uses graphql-code-generator, maybe you could create a template that takes a simple `schema.graphql` file and generates a full server with resolvers and everything for you?

Just an idea.....

**Comment by tomyitav** [comment]
Hi @Urigo , we have an initial version of our cli tool. Check out the [generate-graphql-app](https://github.com/tomyitav/generate-graphql-app) cli. It is currently possible to bootstrap a server from two possible boilerplates, and to easily generate a resolver file from a schema type file. Would be happy to hear your thoughts, enjoy :-)
